version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: node:dubnium-alpine
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: yarn install --production --frozen-lockfile
            - save_cache:
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Run Tests
                  command: yarn test --collectCoverage
            - store_artifacts:
                  path: coverage
